### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Hedon haven - adult content aggregator
email: hedon-haven.7qw93@8shield.net
# description:
baseurl: ""
url: "https://hedon-haven.github.io/"
theme_color: '#00ff00'
# twitter_username: sandochee
github_username:  hedon-haven
author: Hedon haven
logo: assets/images/large-logo.png
twitter:
  username: sandochee
social:
  name: Hedon haven
  links:
    #- https://twitter.com/sandochee
    #- https://www.facebook.com/sandoche
    #- https://www.linkedin.com/in/sandoche
    #- https://plus.google.com/+SandocheADITTANE
    - https://github.com/hedon-haven

languages: ["en"]
ampdir: amp

github: https://github.com/hedon-haven/viewer

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
