name: Mobile App Name
description: A super tagline for the mobile app
# TODO: Add link to full list of supported providers
# TODO: Add link to limitations of platforms
full_description: 'Hedon Haven is a modern, privacy-focused adult content aggregator app for mobile and desktop.<br>
<br>Features:
<br>- Supports different Providers: Enjoy content from a variety of providers such as Pornhub, xHamster and many more.
<br>- Completely Free: Full access to all features with no hidden fees or subscriptions.
<br>- Offline viewing: Download content for offline viewing from any provider.
<br>- Easy management: Favorite videos, subscriptions, and watch history all in one place.
<br>- Privacy-Focused: Designed with privacy-first principles to ensure data security and discretion.
<br>- Open Source: Free and open-source, allowing anyone to contribute or verify the app security.
<br>- Modern Design: A sleek and intuitive interface built with Flutter.
<br>- Supports all platforms: iOS, Android, Windows, macOS, Linux, and Windows. Supported features may vary by platform.'
# TODO: Add f-droid link
# android: https://telegra.ph/Replace-this-link-07-23
#iOS: https://telegra.ph/Replace-this-link-07-23
web: https://github.com/Hedon-haven/viewer/releases/latest/download/all.apk
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
#producthunt: https://telegra.ph/Replace-this-link-07-23
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
